#Configuration file for Videotranscoder: https://github.com/lrissman-github/Videotranscoder
#Note: Relative paths will be based on the base path
######Runtime configs#####

mode: crf #Default mode: crf or 2pass
scale: off #default scaling: off, 480p, 720p, 1080p, or uhd
vcodec: hevc #default output video codec: avc, hevc, vp9
acodec: aac  #Default ouptut audio codec: aac.   Opus to be supported in the future
subtitle: ignore #default mode; ignore.   Or extract.
####### Paths #######

logfile: 'c:\videoprocessing\videotranscoder.log'
loglevel: 'debug'  #info, warning, or debug
#Working Directories
base: 'C:\Users\lriss\PycharmProjects\Videotranscoder'     #location of this script
input: 'c:\videoprocessing\input'
output: 'c:\videoprocessing\output'
unknown: 'c:\videoprocessing\unknown'
bad: 'c:\videoprocessing\bad'
multiaudio: 'c:\videoprocessing\multi'

#Tools
#Windows
tool:
 ffmpeg: 'tools\ffmpeg\ffmpeg.exe'
 ffprobe: 'tools\ffmpeg\ffprobe.exe'
#Linux
 #- ffmpeg: '/usr/bin/ffmpeg'
 #- ffprobe: '/usr/bin/ffprobe'

####### Containers/Files #######
#These are container types that will be allowed, all others will be moved to 'unknown folder'
#   Note: FFMPEG must support any added here
SupportedInputContainers:
 - .avi
 - .avs
 - .divx
 - .m2ts
 - .m4v
 - .mkv
 - .mov
 - .mp4
 - .mpeg
 - .mpg
 - .ogm
 - .vob
 - .webm
 - .wmv

# This is a list of other files, if found, will be moved with the video
ExtraFilesExtensions:
 - .idx
 - .sub
 - .srt
 - .ass
 - .smi

####### Codecs #######
# Note: These Codec names must be written as Mediainfo will report them and supported by FFMPEG

# list of video codecs that could have worthwhile video quality
SupportedInputVideoCodecs:
 - AVC
 - avc1
 - DX50
 - HEVC
 - High Efficiency Video Coding
 - Microsoft
 - 'MPEG-4 Visual'
 - MPEG Video
 - 'VC-1'
 - V_MPEG4/ISO/AVC
 - V_MPEGH/ISO/HEVC
 - WMV3
 - XVID
 - xvid

# Any input video with these will be moved to Bad -- typically codecs known to have a terrible source quality
UnsupportedInputVideoCodecs:
 - DIV3
 - DivX 4

SupportedInputAudioCodecs:
 - AAC
 - 'AC-3'
 - 'E-AC-3'
 - MPEG Audio
 - WMA
 - DTS
 - PCM
 - WMA
 - Atmos / TrueHD
 - FLAC

SupportedInputSubtitles:
  - subrip

####### Quality/Resolution #######
#  This section is to define the minimums and maximums that the script will use to determine if a stream needs transcocding.
#    For example:  If a video codec is already the target output codec and has a resolution and bitrate below the
#      Maximum, then the script will copy that stream instead of transcoding it.
# Note: for Mediainfo, 1K = 1000

#Variance keys are used in a video is slightly larger than target, it will still just copy and not transcode
TargetBitRate:
 vVariance: 1.10   #1.10 = 10%
 avc:
  480p: 699000
  720p: 1500000
  1080p: 2200000
  UHD: 7000000
 hevc:
  480p: 300000
  720p: 720000
  1080p: 1300000
  UHD: 3500000
 vp9:
  480p: 300000
  720p: 720000
  1080p: 1300000
  UHD: 3500000
 aVariance: 1.10   #1.10 = 10%
 aac:
  '2': 64000 #2 Channel
  '6': 256000 #6 Channel
 opus:
  '2': 64000 #2 Channel
  '6': 256000 #6 Channel

#CRF - lower = better quality
# AVC/HEVC CRF: http://slhck.info/video/2017/02/24/crf-guide.html
# VP9 CRF: https://superuser.com/questions/1042194/settings-for-ffmpeg-for-best-vp9-quality-for-web-publishing#1042290

TargetCRF:
 avc:
  480p: 26
  720p: 24
  1080p: 23
  UHD: 21
 hevc:
  480p: 26
  720p: 24
  1080p: 23
  UHD: 21
 vp9:
  480p: 26
  720p: 24
  1080p: 23
  UHD: 21

####### Encoder Settings #######
#  This section is to setup the encoder settings.  Edit this area with care as it could easily break
# Note: AT this time, only FFMPEG is supported.  Future versions are intended to include support for hardware encoders

AVCEncoder:
 480p: ffmpeg
 720p: ffmpeg
 1080p: ffmpeg
 UHD: ffmpeg

HEVCEncoder:
 480p: ffmpeg
 720p: ffmpeg
 1080p: ffmpeg
 UHD: ffmpeg

VP9Encoder:
 480p: ffmpeg
 720p: ffmpeg
 1080p: ffmpeg
 UHD: ffmpeg

#Encoder parameters

#Note Target Bitrate/CRF is appended to this string, so -crf or -b:v must be the last parameter with a trailing space
# VP9 is not implemented yet.

FFMPEG:
  avc:
   copy: '-vcodec copy'
   pass1: '-vcodec libx264 -profile:v high -level 41 -preset fast -b:v '
   pass2: '-vcodec libx264 -profile:v high -level 41 -preset slow -b:v '
   crf: '-vcodec libx264 -profile:v high -level 41 -preset slow -crf '
  hevc:
   copy: '-vcodec copy'
   pass1: '-vcodec libx265 -preset fast -b:v '
   pass2: '-vcodec libx265 -preset slow -b:v '
   crf: '-vcodec libx265 -preset medium -x265-params crf '
  vp9:  #incomplete
   copy: '-vcodec copy'
   pass1: '-vcodec libvpx-vp9 -quality good -b:v '
   pass2: '-vcodec libvpx-vp9 -quality good -b:v '
   crf: '-vcodec libvpx-vp9 -quality good -crf '
  aac:
   copy: '-acodec copy'
   '2': '-acodec aac -ac 2 -strict -2 -ab '
   '6': '-acodec aac -ac 6 -strict -2 -ab '
  opus: #incomplete
   copy: '-acodec copy'
   '2': '-acodec libopus '#...
   '6': '-acodec libopus '#...
  scale: #scale code
   480p: '-vf scale=720:-2'
   720p: '-vf scale=1280:-2'
   1080p: '-vf scale=1920:-2'
   uhd: '-vf scale=3840:-2'
   8kuhd: '-vf scale=7680:-2'
